using ClosedXML.Excel;
using LawMate.Application.AdminModule.AdminReports.Queries;
using LawMate.Application.Common.Interfaces.AdminReports;
using LawMate.Domain.DTOs;
using MediatR;

namespace LawMate.Infrastructure.Services.Reports;

public class MembershipRenewalReportService : IMembershipRenewalReportService
{
    private readonly IMediator _mediator;

    public MembershipRenewalReportService(IMediator mediator)
    {
        _mediator = mediator;
    }

    private static readonly (string Header, Func<MembershipRenewalReportDto, object?> Value)[] Columns =
    [
        ("User ID", r => r.UserId),
        ("Lawyer Name", r => r.LawyerName),
        ("Email", r => r.Email),
        ("Contact Number", r => r.ContactNumber),

        ("Working District", r => r.WorkingDistrict),
        ("Area Of Practice", r => r.AreaOfPractice),
        ("Average Rating", r => r.AverageRating),

        ("Membership Start Date", r => r.MembershipStartDate?.ToString("yyyy-MM-dd") ?? "-"),
        ("Membership End Date", r => r.MembershipEndDate?.ToString("yyyy-MM-dd") ?? "-"),

        ("Membership Fee", r => r.MembershipFee),
        ("Payment Status", r => r.PaymentStatus),
        ("Verification Status", r => r.VerificationStatus),

        ("Membership Expired", r => r.IsExpired ? "Yes" : "No"),
        ("Days Until Expiry", r => r.DaysUntilExpiry),
        ("Membership Status", r => r.MembershipStatusLabel),

        ("Total Renewals", r => r.TotalRenewals)
    ];

    public async Task<byte[]> GenerateMembershipRenewalReportAsync(string generatedByUserId)
    {
        var data = (await _mediator.Send(new GetMembershipRenewalReportQuery())).ToList();

        int totalCols = Columns.Length;

        using var workbook = new XLWorkbook();
        var sheet = workbook.Worksheets.Add("Membership Renewal Report");

        WriteMetaHeader(sheet, generatedByUserId, totalCols);

        const int headerRow = 6;
        WriteColumnHeaders(sheet, headerRow, totalCols);

        int currentRow = headerRow + 1;

        foreach (var row in data)
        {
            for (int col = 1; col <= totalCols; col++)
            {
                var cell = sheet.Cell(currentRow, col);
                cell.Value = XLCellValue.FromObject(Columns[col - 1].Value(row));

                if (currentRow % 2 == 0)
                    cell.Style.Fill.BackgroundColor = XLColor.FromHtml("#F7F7F7");
            }

            currentRow++;
        }

        sheet.ColumnsUsed().AdjustToContents(minWidth: 12, maxWidth: 50);

        sheet.SheetView.FreezeRows(headerRow);

        using var ms = new MemoryStream();
        workbook.SaveAs(ms);

        return ms.ToArray();
    }
    
    private static void WriteMetaHeader(IXLWorksheet sheet, string userId, int totalCols)
    {
        var titleCell = sheet.Cell(1, 1);
        titleCell.Value = "Membership Renewal Report";
        titleCell.Style.Font.Bold = true;
        titleCell.Style.Font.FontSize = 16;
        titleCell.Style.Font.FontColor = XLColor.FromHtml("#1B3A6B");
        titleCell.Style.Alignment.Horizontal = XLAlignmentHorizontalValues.Center;

        sheet.Range(1, 1, 1, totalCols).Merge();

        var brandCell = sheet.Cell(2, 1);
        brandCell.Value = "LawMate";
        brandCell.Style.Font.Bold = true;
        brandCell.Style.Font.FontSize = 12;
        brandCell.Style.Font.FontColor = XLColor.FromHtml("#4A6FA5");
        brandCell.Style.Alignment.Horizontal = XLAlignmentHorizontalValues.Center;

        sheet.Range(2, 1, 2, totalCols).Merge();

        var dateCell = sheet.Cell(3, 1);
        dateCell.Value = $"Generated Date/Time : {DateTime.Now:yyyy-MM-dd  HH:mm:ss}";
        dateCell.Style.Font.FontSize = 10;
        dateCell.Style.Font.Italic = true;
        dateCell.Style.Font.FontColor = XLColor.FromHtml("#555555");
        dateCell.Style.Alignment.Horizontal = XLAlignmentHorizontalValues.Center;

        sheet.Range(3, 1, 3, totalCols).Merge();

        var userCell = sheet.Cell(4, 1);
        userCell.Value = $"Generated By       : {userId}";
        userCell.Style.Font.FontSize = 10;
        userCell.Style.Font.Italic = true;
        userCell.Style.Font.FontColor = XLColor.FromHtml("#555555");
        userCell.Style.Alignment.Horizontal = XLAlignmentHorizontalValues.Center;

        sheet.Range(4, 1, 4, totalCols).Merge();

        sheet.Row(5).Height = 6;
    }

    private static void WriteColumnHeaders(IXLWorksheet sheet, int headerRow, int totalCols)
    {
        for (int col = 1; col <= totalCols; col++)
        {
            var cell = sheet.Cell(headerRow, col);
            cell.Value = Columns[col - 1].Header;

            cell.Style.Font.Bold = true;
            cell.Style.Font.FontColor = XLColor.White;
            cell.Style.Font.FontSize = 10;
            cell.Style.Fill.BackgroundColor = XLColor.FromHtml("#1B3A6B");
            cell.Style.Alignment.Horizontal = XLAlignmentHorizontalValues.Center;
            cell.Style.Alignment.Vertical = XLAlignmentVerticalValues.Center;
            cell.Style.Alignment.WrapText = true;
            cell.Style.Border.OutsideBorder = XLBorderStyleValues.Thin;
            cell.Style.Border.OutsideBorderColor = XLColor.FromHtml("#AAAAAA");
        }

        sheet.Row(headerRow).Height = 30;
    }
}