using ClosedXML.Excel;
using LawMate.Application.AdminModule.AdminReports.Queries;
using LawMate.Application.Common.Interfaces.AdminReports;
using LawMate.Domain.DTOs;
using MediatR;

namespace LawMate.Infrastructure.Services.Reports
{
    public class MonthlyRevenueReportService : IMonthlyRevenueReportService
    {
        private readonly IMediator _mediator;

        public MonthlyRevenueReportService(IMediator mediator)
        {
            _mediator = mediator;
        }

        // Column definitions (order matters — drives header row and data mapping) 
        private static readonly (string Header, Func<MonthlyRevenueReportDto, object?> Value)[] Columns =
        [
            ("Year", r => r.Year),
            ("Month", r => r.MonthName),
            ("Total Bookings", r => r.TotalBookings),
            ("Completed Bookings", r => r.CompletedBookings),
            ("Cancelled Bookings", r => r.CancelledBookings),
            ("Total Revenue (LKR)", r => r.TotalRevenue),
            ("Pending Revenue (LKR)", r => r.PendingRevenue),
            ("Membership Revenue (LKR)", r => r.MembershipRevenue),
            ("New Clients", r => r.NewClients),
            ("New Lawyers", r => r.NewLawyers)
        ];

        public async Task<byte[]> GenerateMonthlyRevenueReportAsync(string generatedByUserId)
        {
            // 1. Fetch data via MediatR query
            var data = (await _mediator.Send(new GetMonthlyRevenueReportQuery())).ToList();

            int totalCols = Columns.Length;

            using var workbook = new XLWorkbook();
            var sheet = workbook.Worksheets.Add("Monthly Revenue Report");

            // META HEADER (rows 1-4)
            WriteMetaHeader(sheet, generatedByUserId, totalCols);

            // COLUMN HEADERS (row 6)
            const int headerRow = 6;
            WriteColumnHeaders(sheet, headerRow, totalCols);

            // DATA ROWS (row 7 onwards)
            int currentRow = headerRow + 1;
            foreach (var row in data)
            {
                for (int col = 1; col <= totalCols; col++)
                {
                    var cell = sheet.Cell(currentRow, col);
                    cell.Value = XLCellValue.FromObject(Columns[col - 1].Value(row));

                    // Subtle alternating row shading
                    if (currentRow % 2 == 0)
                        cell.Style.Fill.BackgroundColor = XLColor.FromHtml("#F7F7F7");
                }
                currentRow++;
            }

            // COLUMN WIDTHS
            sheet.ColumnsUsed().AdjustToContents(minWidth: 12, maxWidth: 50);

            // Freeze pane: keep meta header + column header visible while scrolling
            sheet.SheetView.FreezeRows(headerRow);

            // WRITE TO BYTES
            using var ms = new MemoryStream();
            workbook.SaveAs(ms);
            return ms.ToArray();
        }

        private static void WriteMetaHeader(IXLWorksheet sheet, string userId, int totalCols)
        {
            // Row 1 – Report title
            var titleCell = sheet.Cell(1, 1);
            titleCell.Value = "Monthly Revenue Report";
            titleCell.Style.Font.Bold = true;
            titleCell.Style.Font.FontSize = 16;
            titleCell.Style.Font.FontColor = XLColor.FromHtml("#1B3A6B");   // dark navy
            titleCell.Style.Alignment.Horizontal = XLAlignmentHorizontalValues.Center;
            sheet.Range(1, 1, 1, totalCols).Merge();

            // Row 2 – Brand name
            var brandCell = sheet.Cell(2, 1);
            brandCell.Value = "LawMate";
            brandCell.Style.Font.Bold = true;
            brandCell.Style.Font.FontSize = 12;
            brandCell.Style.Font.FontColor = XLColor.FromHtml("#4A6FA5");
            brandCell.Style.Alignment.Horizontal = XLAlignmentHorizontalValues.Center;
            sheet.Range(2, 1, 2, totalCols).Merge();

            // Row 3 – Generated date/time
            var dateCell = sheet.Cell(3, 1);
            dateCell.Value = $"Generated Date/Time : {DateTime.Now:yyyy-MM-dd  HH:mm:ss}";
            dateCell.Style.Font.FontSize = 10;
            dateCell.Style.Font.Italic = true;
            dateCell.Style.Font.FontColor = XLColor.FromHtml("#555555");
            dateCell.Style.Alignment.Horizontal = XLAlignmentHorizontalValues.Center;
            sheet.Range(3, 1, 3, totalCols).Merge();

            // Row 4 – Generated by
            var userCell = sheet.Cell(4, 1);
            userCell.Value = $"Generated By       : {userId}";
            userCell.Style.Font.FontSize = 10;
            userCell.Style.Font.Italic = true;
            userCell.Style.Font.FontColor = XLColor.FromHtml("#555555");
            userCell.Style.Alignment.Horizontal = XLAlignmentHorizontalValues.Center;
            sheet.Range(4, 1, 4, totalCols).Merge();

            // Row 5 – Blank spacer (leave it empty, just ensure height)
            sheet.Row(5).Height = 6;
        }

        private static void WriteColumnHeaders(IXLWorksheet sheet, int headerRow, int totalCols)
        {
            for (int col = 1; col <= totalCols; col++)
            {
                var cell = sheet.Cell(headerRow, col);
                cell.Value = Columns[col - 1].Header;

                cell.Style.Font.Bold = true;
                cell.Style.Font.FontColor = XLColor.White;
                cell.Style.Font.FontSize = 10;
                cell.Style.Fill.BackgroundColor = XLColor.FromHtml("#1B3A6B");
                cell.Style.Alignment.Horizontal = XLAlignmentHorizontalValues.Center;
                cell.Style.Alignment.Vertical = XLAlignmentVerticalValues.Center;
                cell.Style.Alignment.WrapText = true;
                cell.Style.Border.OutsideBorder = XLBorderStyleValues.Thin;
                cell.Style.Border.OutsideBorderColor = XLColor.FromHtml("#AAAAAA");
            }

            sheet.Row(headerRow).Height = 30;
        }
    }
}