using ClosedXML.Excel;
using LawMate.Application.AdminModule.AdminReports.Queries;
using LawMate.Application.Common.Interfaces.AdminReports;
using LawMate.Domain.DTOs;
using MediatR;

namespace LawMate.Infrastructure.Services.Reports;

public class PlatformCommissionReportService : IPlatformCommissionReportService
{
    private readonly IMediator _mediator;

    public PlatformCommissionReportService(IMediator mediator)
    {
        _mediator = mediator;
    }

    private static readonly (string Header, Func<PlatformCommissionReportDto, object?> Value)[] Columns =
    [
        ("Booking ID", r => r.BookingId),
        ("Scheduled Date/Time", r => r.ScheduledDateTime?.ToString("yyyy-MM-dd HH:mm")),

        // Client
        ("Client Name", r => r.ClientName),
        ("Client Email", r => r.ClientEmail),

        // Lawyer
        ("Lawyer Name", r => r.LawyerName),
        ("Lawyer Email", r => r.LawyerEmail),
        ("Area of Practice", r => r.AreaOfPractice),
        ("Working District", r => r.WorkingDistrict),

        // Booking / Payment
        ("Duration (mins)", r => r.Duration),
        ("Booking Amount", r => r.BookingAmount),
        ("Platform Commission", r => r.PlatformCommission),
        ("Lawyer Payout", r => r.LawyerPayout),
        ("Booking Status", r => r.BookingStatus),
        ("Payment Status", r => r.PaymentStatus),
        ("Transaction ID", r => r.TransactionId),
        ("Payment Date", r => r.PaymentDate?.ToString("yyyy-MM-dd HH:mm")),
        ("Payment Verification Status", r => r.PaymentVerificationStatus)
    ];

    public async Task<byte[]> GeneratePlatformCommissionReportAsync(string generatedByUserId)
    {
        var data = (await _mediator.Send(new GetPlatformCommissionReportQuery())).ToList();

        int totalCols = Columns.Length;

        using var workbook = new XLWorkbook();
        var sheet = workbook.Worksheets.Add("Platform Commission Report");

        WriteMetaHeader(sheet, generatedByUserId, totalCols);

        const int headerRow = 6;
        WriteColumnHeaders(sheet, headerRow, totalCols);

        int currentRow = headerRow + 1;

        foreach (var row in data)
        {
            for (int col = 1; col <= totalCols; col++)
            {
                var cell = sheet.Cell(currentRow, col);
                cell.Value = XLCellValue.FromObject(Columns[col - 1].Value(row));

                if (currentRow % 2 == 0)
                    cell.Style.Fill.BackgroundColor = XLColor.FromHtml("#F7F7F7");
            }

            currentRow++;
        }

        sheet.ColumnsUsed().AdjustToContents(minWidth: 12, maxWidth: 50);
        sheet.SheetView.FreezeRows(headerRow);

        using var ms = new MemoryStream();
        workbook.SaveAs(ms);

        return ms.ToArray();
    }

    // SAME HEADER FORMAT AS OTHER REPORTS
    private static void WriteMetaHeader(IXLWorksheet sheet, string userId, int totalCols)
    {
        var titleCell = sheet.Cell(1, 1);
        titleCell.Value = "Platform Commission Report";
        titleCell.Style.Font.Bold = true;
        titleCell.Style.Font.FontSize = 16;
        titleCell.Style.Font.FontColor = XLColor.FromHtml("#1B3A6B");
        titleCell.Style.Alignment.Horizontal = XLAlignmentHorizontalValues.Center;
        sheet.Range(1, 1, 1, totalCols).Merge();

        var brandCell = sheet.Cell(2, 1);
        brandCell.Value = "LawMate";
        brandCell.Style.Font.Bold = true;
        brandCell.Style.Font.FontSize = 12;
        brandCell.Style.Font.FontColor = XLColor.FromHtml("#4A6FA5");
        brandCell.Style.Alignment.Horizontal = XLAlignmentHorizontalValues.Center;
        sheet.Range(2, 1, 2, totalCols).Merge();

        var dateCell = sheet.Cell(3, 1);
        dateCell.Value = $"Generated Date/Time : {DateTime.Now:yyyy-MM-dd  HH:mm:ss}";
        dateCell.Style.Font.FontSize = 10;
        dateCell.Style.Font.Italic = true;
        dateCell.Style.Font.FontColor = XLColor.FromHtml("#555555");
        dateCell.Style.Alignment.Horizontal = XLAlignmentHorizontalValues.Center;
        sheet.Range(3, 1, 3, totalCols).Merge();

        var userCell = sheet.Cell(4, 1);
        userCell.Value = $"Generated By       : {userId}";
        userCell.Style.Font.FontSize = 10;
        userCell.Style.Font.Italic = true;
        userCell.Style.Font.FontColor = XLColor.FromHtml("#555555");
        userCell.Style.Alignment.Horizontal = XLAlignmentHorizontalValues.Center;
        sheet.Range(4, 1, 4, totalCols).Merge();

        sheet.Row(5).Height = 6;
    }

    private static void WriteColumnHeaders(IXLWorksheet sheet, int headerRow, int totalCols)
    {
        for (int col = 1; col <= totalCols; col++)
        {
            var cell = sheet.Cell(headerRow, col);
            cell.Value = Columns[col - 1].Header;

            cell.Style.Font.Bold = true;
            cell.Style.Font.FontColor = XLColor.White;
            cell.Style.Font.FontSize = 10;
            cell.Style.Fill.BackgroundColor = XLColor.FromHtml("#1B3A6B");
            cell.Style.Alignment.Horizontal = XLAlignmentHorizontalValues.Center;
            cell.Style.Alignment.Vertical = XLAlignmentVerticalValues.Center;
            cell.Style.Alignment.WrapText = true;
            cell.Style.Border.OutsideBorder = XLBorderStyleValues.Thin;
            cell.Style.Border.OutsideBorderColor = XLColor.FromHtml("#AAAAAA");
        }

        sheet.Row(headerRow).Height = 30;
    }
}